# Generated by Django 4.1.2 on 2022-10-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0007_alter_tag_name"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="guild",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="ads.guild"
            ),
        ),
    ]
