# Generated by Django 4.1.2 on 2022-10-17 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0009_reply"),
        ("users", "0002_user_guild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ads.guild",
            ),
        ),
    ]
