# Generated by Django 4.1.2 on 2022-10-28 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0016_alter_ad_content_alter_ad_guild_and_more"),
        ("users", "0003_alter_user_guild"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="pics/%Y/%m/%d/", verbose_name="Аватар"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ads.guild",
                verbose_name="Гильдия",
            ),
        ),
    ]
