# Generated by Django 4.1.2 on 2022-10-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_avatar_alter_user_guild"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["username"]},
        ),
    ]
