# Generated by Django 4.1.2 on 2022-11-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_subscribed",
            field=models.BooleanField(default=0, verbose_name="Подписан на рассылку"),
            preserve_default=False,
        ),
    ]
