# Generated by Django 4.1.2 on 2023-08-15 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="reply",
            name="parent_ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ads.ad"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="guild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ads.guild",
                verbose_name="Гильдия",
            ),
        ),
    ]
