# Generated by Django 4.1.2 on 2022-10-16 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0004_alter_ad_media_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ad",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="guild",
            name="name",
            field=models.CharField(
                max_length=25, null=True, unique=True, verbose_name="Наименование"
            ),
        ),
    ]
