# Generated by Django 4.1.2 on 2022-10-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0005_ad_author_alter_ad_title_alter_guild_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guild",
            name="name",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="Наименование"
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Метка"
                    ),
                ),
                ("ads", models.ManyToManyField(db_table="ads_tags", to="ads.ad")),
            ],
            options={
                "verbose_name": "Метка",
                "verbose_name_plural": "Метки",
                "ordering": ["name"],
            },
        ),
    ]
