# Generated by Django 4.1.2 on 2022-10-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0009_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="ads",
            field=models.ManyToManyField(
                blank=True, db_table="ads_tags", null=True, to="ads.ad"
            ),
        ),
    ]
