# Generated by Django 4.1.2 on 2022-10-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0013_alter_reply_guild"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reply",
            name="guild",
        ),
        migrations.AddField(
            model_name="ad",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ads.guild",
            ),
        ),
    ]
