# Generated by Django 4.1.2 on 2022-10-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0014_remove_reply_guild_ad_guild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="guild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ads.guild"
            ),
        ),
    ]
