# Generated by Django 4.1.2 on 2022-10-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0015_alter_ad_guild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="content",
            field=models.TextField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="guild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ads.guild",
                verbose_name="Гильдия",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="media_content",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pics/%Y/%m/%d/",
                verbose_name="Изображение/Видео",
            ),
        ),
    ]
