# Generated by Django 4.1.2 on 2022-10-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0016_alter_ad_content_alter_ad_guild_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="accepted",
            field=models.BooleanField(null=True, verbose_name="Принят"),
        ),
    ]
