# Generated by Django 4.1.2 on 2022-10-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0017_reply_accepted"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplyAcceptedOrNull",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Текст")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата редактирования"
                    ),
                ),
                ("accepted", models.BooleanField(null=True, verbose_name="Принят")),
            ],
            options={
                "verbose_name": "Отклик",
                "verbose_name_plural": "Отклики",
                "db_table": "vw_replies_accepted_or_null",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
    ]
