# Generated by Django 4.1.2 on 2022-11-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0018_replyacceptedornull"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReplyAcceptedOrNull",
        ),
    ]
